title: Tangli Ge

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Research"
   link: "/researcher/"
 - name: "Teaching"
   link: "/teaching/"
 - name: "Activities"
   link: "/activities/"

