title: Jiaxi Wu

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://scholar.google.com/citations?user=Z-CTMmsAAAAJ&hl=en&oi=sra"
footer_text: Last updated date: Oct 9, 2022

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Research"
   link: "research"
 - name: "Featured Projects"
   link: "featured projects"
 - name: "Publication"
   link: "publication"
 - name: "Teaching"
   link: "teaching"
 - name: "CV"
   link: "JiaxiWuCV.pdf"


