title: Jiaxi Wu

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Research"
   link: "research"
 - name: "Teaching"
   link: "teaching"
 - name: "Publication"
   link: "publication"
 - name: "CV"
   link: "cv"
 - name: "Contact"
   link: "contact"

