title: Jiaxi Wu

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: Last Updated: September 11, 2022

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Research"
   link: "research"
 - name: "Featured Projects"
   link: "featured projects"
 - name: "Publication"
   link: "publication"
 - name: "Teaching"
   link: "teaching"
 - name: "CV"
   link: "JiaxiWu_CV.pdg"


